### ISSUE TITLE
Recherche Historische Versionen

### ISSUE THREAD

**Issue by mme1950** [ASJeton/Klassenvorschrift#1]
Wir wollen die "offizielle" Version der Klassenvorschrift identifizieren und ggf. noch vorhandene historische Versionen finden.

**Comment by mme1950** [comment]
[Die "offizielle" Version von der ASJETON-Website](https://www.segel.de/jeton/index_htm_files/Klassenvorschrift%20der%20Jeton-Klasse.pdf)

@daniel-richter Die Fassung im Repository scheint mir identisch damit zu sein.

**Comment by mme1950** [comment]
Ich habe noch "echte" ältere Versionen gefunden:
* JKV 1993.DOC
* JKV_1997.doc

Dies scheint ein Zwischenentwurf zu sein:
* Jkv_2000 _o.doc

Hier fehlt der Kopf:
* JKV.DOC

[JKV.zip](https://github.com/ASJeton/Klassenvorschrift/files/6771435/JKV.zip)

**Comment by mme1950** [comment]
Das habe ich ach noch gefunden, abgelegt in Ordner 2000. Ich kann mich nicht erinnern.
[JKV.zip](https://github.com/ASJeton/Klassenvorschrift/files/6771510/JKV.zip)

**Comment by mme1950** [comment]
Von 2002 habe ich dieses Schreiben:
[Änderung der Klassenvorschrift.zip](https://github.com/ASJeton/Klassenvorschrift/files/6771515/Anderung.der.Klassenvorschrift.zip)

**Comment by mme1950** [comment]
Und dann habe ich noch dieses txt-Dokument. Das ist offenbar neuer als das auf der Website.
[JKV-2014.zip](https://github.com/ASJeton/Klassenvorschrift/files/6771550/JKV-2014.zip)

**Comment by daniel-richter** [comment]
> [Die "offizielle" Version von der ASJETON-Website](https://www.segel.de/jeton/index_htm_files/Klassenvorschrift%20der%20Jeton-Klasse.pdf)
> 
> @daniel-richter Die Fassung im Repository scheint mir identisch damit zu sein.

Ja, genau. Es gab 2014 noch eine Änderung, die laut @Andreas-Jeton leider nicht im Gesamtdokument fortgeführt wurde - die Änderungen würde ich noch übernehmen (bin bisher noch nicht dazu gekommen)
https://www.dsv.org/nachrichten/offizielle-mitteilungen/2013/04/amtliche-mitteilungen-in-der-yacht-nr-9-vom-10-04-13/

**Comment by daniel-richter** [comment]
Vielen Dank für die älteren Versionen! Ich werde dann die Repo-History so (um)schreiben, dass man den Verlauf sehen kann.

**Comment by mme1950** [comment]
Super.
Mein txt-Dokument scheint das von 2014 zu sein. Vieleicht sollte ich versuchen, noch die Quelle davon zu finden. Aber möglicherweise ist es einfacher die Änderungen dann einfach ins Repository einzupflegen.

**Comment by daniel-richter** [comment]
Die offizielle Quelle für die 2014er Änderung ist die [Amtliche Mitteilungen in der Yacht Nr. 9 vom 10.04.13](https://www.dsv.org/nachrichten/offizielle-mitteilungen/2013/04/amtliche-mitteilungen-in-der-yacht-nr-9-vom-10-04-13/) vom Deutschen Seglerverband. Die Änderungen würde ich so übernehmen - den Verlauf (bzw. Hintergrund dazu) habe ich auch da (dank @Andreas-Jeton).

**Comment by daniel-richter** [comment]
Die Anpassungen im Laufe der Jahre ggf. mit Begründungen/Kommentaren sind jetzt in den Commits einsehbar:

0858cfd3bc4e7f001cf9294dec659368ea7cdaf7 In den Regeln 6.2, 16.9, 16.10.2, 18: Genehmigung DSV vom 29.11.2002, in Kraft ab 01.04.2003  
cf17656bb7dce6120f94a6ffa5c3e2eae7b50776 In den Regeln 2.2 und 5.4: Genehmigung DSV vom 28.11.2003, in Kraft ab 01.04.2004  
6b3775d74bb2c33d984ce7d0737f5ad43332598e In den Regeln 8.2.5, 8.3.6, 8.4.1, 14.3 und 17.5.3: Genehmigung DSV vom 10.04.2013, in Kraft ab 01.04.2013
