### ISSUE TITLE
Antrag auf Änderung der Klassenvorschrift an DSV senden

### ISSUE THREAD

**Issue by mme1950** [ASJeton/Klassenvorschrift#5]
Die in der Klassenversammlung beschlossenen Änderungen der Klassenvorschrift (Tickets #2. #3, #4) sollen an den DSV geschickt werden, damit diese im technischen Ausschuss des DSV verhandelt werden können.

@Andreas-Jeton, @daniel-richter Könntet ihr den Antrag bitte gegenlesen.

[Antrag auf Änderung der Klassenvorschrift der Jeton-Klasse.docx](https://github.com/ASJeton/Klassenvorschrift/files/7875080/Antrag.auf.Anderung.der.Klassenvorschrift.der.Jeton-Klasse.docx)
[Messblatt2](https://user-images.githubusercontent.com/76402452/149624182-c66f13c9-9b29-439b-8c1a-422a08dba869.png)
.

**Comment by daniel-richter** [comment]
Zum Inhalt: Die Segelnummer im Spi (siehe https://github.com/ASJeton/Klassenvorschrift/issues/2#issuecomment-994941663) wurde nicht mit aufgenommen?

Zur Form: Wollen wir den alten Text der Klassenvorschrift noch mit aufnehmen? (Damit man die Änderungen besser sieht)

**Comment by mme1950** [comment]
Nur die Absätze 6.2 und 63 habe ich mit "Schreibe neu" angegeben, 6.1 und 6.4 ...Spinnaker... ist unverändert. Allerdings hätte man da Unterscheidzungsnummer durch Segelnummer ersetzen sollen.

**Comment by daniel-richter** [comment]
Wie ist denn der aktuelle Stand? Bzw. der genaue Wortlaut der (geplanten) Änderungen?

**Comment by mme1950** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/mme/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/mme/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/mme/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/mme/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE link="#0563C1" vlink="#954F72" style='tab-interval:35.4pt;
word-wrap:break-word'>


<p class=MsoNormal>Hallo Frau Wittkugel,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>anliegend erhalten sie das Protokoll der
Jahreshauptversammlung der ASJETON vom 31.Juli2021 und die Liste der anwesenden
Mitglieder. <o:p></o:p></p>

<p class=MsoNormal>In meinem Antrag hatte ich versehentlich ein falsches Datum
der Mitgliederversammlung angegeben. Der Antrag mit dem korrigierten Datum
liegt ebenfalls bei.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Die Sitzung des Technischen Ausschusses werde ich gerne
verfolgen und bitte Sie daher um die Zusendung des Links. <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Mit freundlichen Grüßen<o:p></o:p></p>

<p class=MsoNormal>Matthias Menningen<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>______________________________________________________________<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>Dr. Matthias Menningen<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>ASJETON, Technischer Beauftragter<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>m: +49 (1578) 2 88 44 33 <o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='mso-fareast-language:
DE'>Von:</span></b><span style='mso-fareast-language:DE'> Wittkugel, Kristina
&lt;<a href="mailto:Kristina.Wittkugel@dsv.org">Kristina.Wittkugel@dsv.org</a>&gt;
<br>
<b>Gesendet:</b> Donnerstag, 27. Januar 2022 11:48<br>
<b>An:</b> Dr. Matthias Menningen &lt;<a
href="mailto:matthias.menningen@nanologika.de">matthias.menningen@nanologika.de</a>&gt;<br>
<b>Cc:</b> <a href="mailto:Technik@dsv.org">Technik@dsv.org</a><br>
<b>Betreff:</b> AW: Änderung der Klassenvorschrift der Jeton-Klasse<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>Guten Tag Herr
Dr. Menningen,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>bitte schicken
Sie uns noch das Protokoll der Jahreshauptversammlung der KV zu, aus dem
hervorgeht, dass über den Antrag abgestimmt und dieser angenommen wurde.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>Zudem benötigen
wir eine Kopie der Teilnehmerliste dieser JHV.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>Bitte schicken
Sie uns beide Unterlagen so schnell wie möglich zu, damit Ihr Antrag
vollständig ist .<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoPlainText><span style='font-family:"Arial",sans-serif;mso-fareast-language:
EN-US'>Die Sitzung des Technischen Ausschuss findet am 11.02.2022 per
Videokonferenz statt.<o:p></o:p></span></p>

<p class=MsoPlainText><span style='font-family:"Arial",sans-serif;mso-fareast-language:
EN-US'>Bitte teilen Sie uns mit, ob Sie an dieser Sitzung teilnehmen möchten.<o:p></o:p></span></p>

<p class=MsoPlainText><span style='font-family:"Arial",sans-serif;mso-fareast-language:
EN-US'>Wir würden Ihnen dann Bescheid geben, wann in etwa Ihr
Tagesordnungspunkt behandelt wird und Ihnen dann einen Link schicken. <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:12.75pt'><span style='font-family:"Arial",sans-serif;
color:black;mso-fareast-language:DE'>Mit freundlichem Gruß<br>
<br>
Kristina Wittkugel<br>
Assistentin Abteilung Technik und Seeregatten<o:p></o:p></span></p>

<p class=MsoNormal style='line-height:12.75pt'><span style='mso-fareast-language:
DE'>**************************************************<br>
</span><span style='font-family:"Arial",sans-serif;mso-fareast-language:DE'>Deutscher
Segler-Verband e. V.<br>
Soling 16, 24159 Kiel-Schilksee<br>
Tel: +49 40 632009 - 961<br>
Fax: +49 40 632009 - 28<br>
<a href="https://www.dsv.org/">www.dsv.org</a><br>
**************************************************<o:p></o:p></span></p>



 
--




<p class=MsoNormal><span style='mso-fareast-language:DE'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='mso-fareast-language:
DE'>Von:</span></b><span style='mso-fareast-language:DE'> Dr. Matthias
Menningen &lt;<a href="mailto:matthias.menningen@nanologika.de">matthias.menningen@nanologika.de</a>&gt;
<br>
<b>Gesendet:</b> Sonntag, 16. Januar 2022 17:34<br>
<b>An:</b> <a href="mailto:Technik@dsv.org">Technik@dsv.org</a><br>
<b>Cc:</b> Andreas Rademacher &lt;<a href="mailto:grastaenzer@web.de">grastaenzer@web.de</a>&gt;<br>
<b>Betreff:</b> Änderung der Klassenvorschrift der Jeton-Klasse<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Hallo Herr Christophers,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>anliegend finden sie den Antrag auf Änderung der
Klassenvorschrift der Jeton-Klasse.<o:p></o:p></p>

<p class=MsoNormal>Wie telefonisch besprochen, enthält der Antrag die
Beschreibung, Begründung und Formulierungen der Änderungen.<o:p></o:p></p>

<p class=MsoNormal>Außerdem beigefügt ist das geänderte Messblatt 2 zur
Klassenvorschrift.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Bei Rückfragen stehe ich gerne telefonisch zur Verfügung.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Mit freundlichen Grüßen<o:p></o:p></p>

<p class=MsoNormal>Matthias Menningen<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>______________________________________________________________<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>Dr. Matthias Menningen<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>ASJETON, Technischer Beauftragter<o:p></o:p></span></p>

<p class=MsoNormal style='text-autospace:none'><span style='font-size:10.0pt;
mso-fareast-language:DE'>m: +49 (1578) 2 88 44 33 <o:p></o:p></span></p>


</body>

</html>
Hallo Frau Wittkugel,

anliegend erhalten sie das Protokoll der Jahreshauptversammlung der ASJETON vom 31.Juli2021 und die Liste der anwesenden Mitglieder. 
In meinem Antrag hatte ich versehentlich ein falsches Datum der Mitgliederversammlung angegeben. Der Antrag mit dem korrigierten Datum liegt ebenfalls bei.

Die Sitzung des Technischen Ausschusses werde ich gerne verfolgen und bitte Sie daher um die Zusendung des Links. 

Mit freundlichen Grüßen
Matthias Menningen

______________________________________________________________
Dr. Matthias Menningen
ASJETON, Technischer Beauftragter
m: +49 (1578) 2 88 44 33 



Von: Wittkugel, Kristina <[Kristina.Wittkugel@dsv.org](mailto:Kristina.Wittkugel@dsv.org)> 
Gesendet: Donnerstag, 27. Januar 2022 11:48
An: Dr. Matthias Menningen <[matthias.menningen@nanologika.de](mailto:matthias.menningen@nanologika.de)>
Cc: [Technik@dsv.org](mailto:Technik@dsv.org)
Betreff: AW: Änderung der Klassenvorschrift der Jeton-Klasse

Guten Tag Herr Dr. Menningen,

bitte schicken Sie uns noch das Protokoll der Jahreshauptversammlung der KV zu, aus dem hervorgeht, dass über den Antrag abgestimmt und dieser angenommen wurde.
Zudem benötigen wir eine Kopie der Teilnehmerliste dieser JHV.

Bitte schicken Sie uns beide Unterlagen so schnell wie möglich zu, damit Ihr Antrag vollständig ist .

Die Sitzung des Technischen Ausschuss findet am 11.02.2022 per Videokonferenz statt.
Bitte teilen Sie uns mit, ob Sie an dieser Sitzung teilnehmen möchten.
Wir würden Ihnen dann Bescheid geben, wann in etwa Ihr Tagesordnungspunkt behandelt wird und Ihnen dann einen Link schicken. 


Mit freundlichem Gruß

Kristina Wittkugel
Assistentin Abteilung Technik und Seeregatten
**************************************************
Deutscher Segler-Verband e. V.
Soling 16, 24159 Kiel-Schilksee
Tel: +49 40 632009 - 961
Fax: +49 40 632009 - 28
[www.dsv.org](https://www.dsv.org/)
**************************************************
 

Generalsekretär: Dr. Germar Brockmeyer
Registereintrag: Vereinsregister-Nr. 1503 beim AG Berlin (Charlottenburg)
Informationen nach Art. 12 ff. DS-GVO zum Umgang mit Ihren personenbezogenen Daten finden Sie unter: [www.dsv.org/datenschutz](https://www.dsv.org/datenschutz)

Abonnieren Sie unseren Newsletter unter: [www.dsv.org/newsletter/](https://www.dsv.org/newsletter/)
Der DSV auf:	 
 
Das German Sailing Team auf:	 
 
 



Von: Dr. Matthias Menningen <[matthias.menningen@nanologika.de](mailto:matthias.menningen@nanologika.de)> 
Gesendet: Sonntag, 16. Januar 2022 17:34
An: [Technik@dsv.org](mailto:Technik@dsv.org)
Cc: Andreas Rademacher <[grastaenzer@web.de](mailto:grastaenzer@web.de)>
Betreff: Änderung der Klassenvorschrift der Jeton-Klasse

Hallo Herr Christophers,

anliegend finden sie den Antrag auf Änderung der Klassenvorschrift der Jeton-Klasse.
Wie telefonisch besprochen, enthält der Antrag die Beschreibung, Begründung und Formulierungen der Änderungen.
Außerdem beigefügt ist das geänderte Messblatt 2 zur Klassenvorschrift.

Bei Rückfragen stehe ich gerne telefonisch zur Verfügung.

Mit freundlichen Grüßen
Matthias Menningen

______________________________________________________________
Dr. Matthias Menningen
ASJETON, Technischer Beauftragter
m: +49 (1578) 2 88 44 33

**Comment by mme1950** [comment]
Der Antrag wurde am 15.01.2022 eingereicht.

Am 20.01.2022 wurde das Protokoll und die Anwesenheitskiste der Klassenversammlung nachgeliefert.

[Antrag.auf.Anderung.der.Klassenvorschrift.der.Jeton-Klasse (1).docx](https://github.com/ASJeton/Klassenvorschrift/files/8776970/Antrag.auf.Anderung.der.Klassenvorschrift.der.Jeton-Klasse.1.docx)

[2021_Protokoll Vorstandswahl - unterzeichnet.pdf](https://github.com/ASJeton/Klassenvorschrift/files/8776977/2021_Protokoll.Vorstandswahl.-.unterzeichnet.pdf)

[ASJETON-KV-2021_Teilnehmerliste.pdf](https://github.com/ASJeton/Klassenvorschrift/files/8776981/ASJETON-KV-2021_Teilnehmerliste.pdf)

**Comment by mme1950** [comment]
Mail vom 21.02.2022

Hallo Herr Menningen,
nach der Sitzung des TA sind wir Ihnen noch eine Antwort auf die Anträge schuldig.
In den offiziellen Mitteilungen finden Sie die offizielle Nachricht zu Ihren Anträgen. Sie werden in den nächsten beiden Wochen online sein.

Inhaltlich hatten wir ja bereits während der Sitzung über die Themen gesprochen. Vielen Dank, daß Sie sich die Zeit dafür genommen haben.
Bzgl der Kennzeichnung in den Segeln: 
Bitte berücksichtigen Sie die in den WR auf Seite 229 Regel G1.2 ff Regularien in Ihrer Überarbeitung des Textes. 

Schwertdrehpunkt:
Dem Antrag wurde stattgegeben.

Schwerttisch:
Der Schwerttisch kann mit einer Lage Sichtcarbon belegt werden, bitte stellen Sie sicher, daß es sich hier nicht um strukturelles Carbon handelt und nur der Schwertkastentisch damit belegt wird. 


Wenn Sie noch Rückfragen haben, lassen Sie es mich gerne wissen,

danke und beste Grüße

Johannes Christophers
Leitung Technik und Seeregatten /
Head of Technical Departement and Offshore Racing
**************************************************
Deutscher Segler-Verband e. V.
Soling 16, 24159 Kiel-Schilksee
Tel: +49 40 632009 - 963
Fax: +49 40 632009 - 28
Mobil: +49 0160 90 83 29 56

**Comment by bernhardrabe-jeton** [comment]
Wurde am 01.04.2022 genehmigt https://www.dsv.org/app/uploads/offizielle-mitteilung-des-technischen-ausschusses-des-dsv-2022.pdf
